name: CI
on:
    push:

jobs:
    release-please:
        name: Release
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        outputs:
            release_created: ${{ steps.release-please.outputs.release_created }}
        steps:
            - uses: googleapis/release-please-action@v4
              id: release-please
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

    publish:
        name: Publish DevOps Extension
        needs: release-please
        if: needs.release-please.outputs.release_created == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
            - name: Install dependencies
              working-directory: ./commitscribe
              run: npm ci
            - name: Build TypeScript
              working-directory: ./commitscribe
              run: npm run build
            - name: Convert task.jsonc to task.json
              working-directory: ./commitscribe
              run: sed 's/\s*\/\/ x-release-please.*$//' task.jsonc > task.json
            - name: Install tfx-cli
              run: npm install -g tfx-cli
            - name: Publish to Marketplace
              run: tfx extension publish --manifest-globs vss-extension.json --publisher ScottMcKendry --token ${{ secrets.MARKETPLACE_TOKEN }}
              env:
                  MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
